#!/bin/bash

# Create the dmz and cluster networks as the external and
# internal networks of the ohpc cluster

# create the dmz network for the head node to attach 
openstack network create dmznet

openstack subnet create --subnet-range 192.168.100.0/24 --dns-nameserver 8.8.8.8 --network dmznet dmzsubnet

# connect dmz to the internet
openstack router create borderrouter

openstack router set borderrouter --external-gateway bright-external-flat-externalnet

openstack router add subnet borderrouter dmzsubnet

# create the cluster network for the compute nodes
openstack network create clusternet

openstack subnet create --subnet-range 10.1.1.0/24 --no-dhcp --network clusternet clustersubnet
